---
title: "Projet Exploratoire"
author: "Vassili ZARCH, Tristan Mathon,Coemgen Genevey"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval = TRUE,warning=FALSE, fig.show="hold", out.width="50%",cache = TRUE)
```

# Introduction

## but

```{r}
library(class)
source("color_utils.R")
```

Le but de ce projet est d'évaluer et de comparer les performances de l'algorithme des K plus proche voisin dans le cadre de la reconstitution d'images bruitées.

```{r}
library("png")
originale<- readPNG("StarWars.png")

pourcent1<- readPNG("Image1pourcent.png")
pourcent10<- readPNG("Image10pourcent.png")
pourcent15<- readPNG("Image15pourcent.png")
pourcent20<- readPNG("Image20pourcent.png")
pourcent25<- readPNG("Image25pourcent.png")
pourcent50<- readPNG("Image50pourcent.png")
```

```{r}
test <- function(k){
  Kopti=5#le nombre optimal de voisins pour la reconstruction de l'image (mse le plus bas)
  result = c()
  result1 = c()
  result10 = c()
  result15 = c()
  result20 = c()
  result25 = c()
  result50 = c()
  for (q in 1:k) {
      kppv1=kppv(pourcent1,q)#reconstruit l'image avec q voisins
      result1 = cbind(result1,mse(originale,kppv1))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 1% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("1% de bruitage et k=",Kopti))
        rasterImage(kppv1, 0, 1, 1, 2)
      }
      
      kppv10=kppv(pourcent10,q)#reconstruit l'image avec q voisins
      result10 = cbind(result10,mse(originale,kppv10))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 10% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("10% de bruitage et k=",Kopti))
        rasterImage(kppv10, 0, 1, 1, 2)
      }
      
      kppv15=kppv(pourcent15,q)#reconstruit l'image avec q voisins
      result15 = cbind(result15,mse(originale,kppv15))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 15% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("15% de bruitage et k=",Kopti))
        rasterImage(kppv15, 0, 1, 1, 2)
      }
      
      kppv20=kppv(pourcent20,q)#reconstruit l'image avec q voisins
      result20 = cbind(result20,mse(originale,kppv20))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 20% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("20% de bruitage et k=",Kopti))
        rasterImage(kppv20, 0, 1, 1, 2)
      }
      
      kppv25=kppv(pourcent25,q)#reconstruit l'image avec q voisins
      result25 = cbind(result25,mse(originale,kppv25))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 25% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("25% de bruitage et k=",Kopti))
        rasterImage(kppv25, 0, 1, 1, 2)
      }
      
      kppv50=kppv(pourcent50,q)#reconstruit l'image avec q voisins
      result50 = cbind(result50,mse(originale,kppv50))#calcul l'erreur par rapport à l'image originale
      #afficher la reconstitution de l'image bruitée à 50% pour Kopti voisins
      if(q==Kopti){
        plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("50% de bruitage et k=",Kopti))
        rasterImage(kppv50, 0, 1, 1, 2)
      }
      
      #afficher les reconstitutions de l'image bruitée à 50% pour 1 à k voisins
      plot(0:2, 0:2, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "", main = paste("50% de bruitage et k=",q))
      rasterImage(kppv50, 0, 1, 1, 2)
  }
  result =  cbind(result,result1) 
  result =  cbind(result,result10) 
  result =  cbind(result,result15) 
  result =  cbind(result,result20) 
  result =  cbind(result,result25) 
  result =  cbind(result,result50) 
  return(result)
}
```

```{r}
mse <- function(imageO, imageP){
  return(mean((imageO-imageP)^2))
}
```



```{r}
kppv<-function(tab,k = 1){
  if(length(dim(tab))>3){
    stop("dimension supérieur à 3")
  }
  tableau = (tab[,,1] == 1) & (tab[,,2] == 1) & (tab[,,3] == 1) 
  width = ncol(tab)
  heigth = nrow(tab)
  for (x in  1:width) {
    for (y in 1:heigth) {
      if (isTRUE(tableau[x,y])){ #on veut corriger les pixels blancs
        value = sub_kppv(k,tab,tableau,x,y)
        tab[x,y,1] = value$rouge
        tab[x,y,2] = value$vert
        tab[x,y,3] = value$bleu
      }
    }
  }
  return(tab)
}
```

```{r}
sub_kppv <- function(k,tab,tableau,x,y){
  distance = 1 #distance au pixel x,y
  weights = 0;
  tab_list_R = c()
  tab_list_G = c()
  tab_list_B = c()
  width = ncol(tab)
  height = nrow(tab)
  compte = 0 #nombre de voisin récupérer
  if(k == compte){
    return()
  }
  while(compte < k){
    xmin = x - distance #coté gauche du carré des voisins
    xmax = x + distance # coté droit
    ymin = y - distance # coté bas 
    ymax = y + distance # coté haut
    for(i in xmin:xmax){ # on fait le tour du carré représentant les voisins
      for(j in ymin:ymax){
        if(i != 0 | j != 0 ){ #on ne veut pas du pixel 0:0
          if (i >= 0 & j>=0 & i <width & j<height){ #on veut rester dans l'image
            if(isFALSE(tableau[i,j])){  #on veut pas prendre d'autres pixels blancs
              weigth = 1/distance
              tab_list_R = append(tab_list_R,(tab[i,j,1])*weigth) 
              tab_list_G = append(tab_list_G,(tab[i,j,2])*weigth)
              tab_list_B = append(tab_list_B,(tab[i,j,3])*weigth)
              weights = weights + weigth
              compte = compte +1
              if(compte  == k){
                result = c()
                result$rouge = sum(tab_list_R)/weights  #moyenne rouge des voisins
                result$vert = sum(tab_list_G)/weights  #moyenne vert
                result$bleu = sum(tab_list_B)/weights  #moyenne bleu
                return(result)
              }
            }
          }
        }
      }
    }
    distance = distance + 1
  }
}
```

```{r cache=TRUE}

tableau_result = test(8)
```

```{r cache=TRUE}
tableau_result
valuesMSE = c()
for (value in tableau_result) {
  valuesMSE = append(valuesMSE,value)
}
plot(valuesMSE,col = 'RED')
abline(v = 8.5)
abline(v = 16.5)
abline(v = 24.5)
abline(v = 32.5)
abline(v = 40.5)

print("MSE pour 1 à 8 voisins sur 50% de bruit")
for(i in 41 : 48){print(tableau_result[i])}

print("MSE pour 5 voisins sur 1%, 10%, 15%, 20%, 25% et 50% de bruit")
print(tableau_result[5])
print(tableau_result[13])
print(tableau_result[21])
print(tableau_result[29])
print(tableau_result[37])
print(tableau_result[45])
```
